export const products = [
  { id: "styro-15", name: "Styropian 15cm", pricePerM2: 98, thickness: "15cm" },
  { id: "styro-20", name: "Styropian 20cm", pricePerM2: 125, thickness: "20cm" },
  { id: "styro-25", name: "Styropian 25cm", pricePerM2: 155, thickness: "25cm" },
  { id: "styro-30", name: "Styropian 30cm", pricePerM2: 185, thickness: "30cm" },
  { id: "wata-30", name: "Wata mineralna 30cm", pricePerM2: 65, thickness: "30cm" },
  { id: "wata-50", name: "Wata mineralna 50cm", pricePerM2: 95, thickness: "50cm" },
  { id: "wata-100", name: "Wata mineralna 100cm", pricePerM2: 175, thickness: "100cm" },
  { id: "piana-30", name: "Pianka poliuretanowa 30cm", pricePerM2: 145, thickness: "30cm" },
  { id: "piana-50", name: "Pianka poliuretanowa 50cm", pricePerM2: 225, thickness: "50cm" },
  { id: "cegla-30", name: "Cegła ceramiczna 30x25x11.5cm", pricePerM2: 35, thickness: "11.5cm" },
  { id: "cegla-sil", name: "Cegła silikatowa 30x25x11.5cm", pricePerM2: 28, thickness: "11.5cm" },
  { id: "bloczek-12", name: "Bloczek betonowy 12cm", pricePerM2: 42, thickness: "12cm" },
  { id: "bloczek-20", name: "Bloczek betonowy 20cm", pricePerM2: 65, thickness: "20cm" },
  { id: "bloczek-25", name: "Bloczek betonowy 25cm", pricePerM2: 78, thickness: "25cm" },
  { id: "malta-cis", name: "Malta cementowa do murowania", pricePerM2: 15, thickness: "1 opakowanie" },
  { id: "malta-wapien", name: "Malta wapienno-cementowa", pricePerM2: 18, thickness: "1 opakowanie" },
  { id: "beton-c20", name: "Beton C20", pricePerM2: 220, thickness: "1 m³" },
  { id: "beton-c25", name: "Beton C25", pricePerM2: 245, thickness: "1 m³" },
  { id: "beton-c30", name: "Beton C30", pricePerM2: 275, thickness: "1 m³" },
  { id: "dach-pap", name: "Papę dachową 10m2", pricePerM2: 85, thickness: "1 rolka" },
  { id: "dach-bud", name: "Budulce dachowe 1m2", pricePerM2: 45, thickness: "1m2" },
  { id: "dach-mem", name: "Membranę dachową 1m2", pricePerM2: 55, thickness: "1m2" },
  { id: "dachy-kry", name: "Dachówki ceramiczne", pricePerM2: 125, thickness: "1m2" },
  { id: "dachy-bet", name: "Dachówki betonowe", pricePerM2: 95, thickness: "1m2" },
  { id: "gips-1", name: "Gips kartonowy 12.5mm", pricePerM2: 8, thickness: "1m2" },
  { id: "gips-2", name: "Gips kartonowy 15mm", pricePerM2: 10, thickness: "1m2" },
  { id: "mas-glif", name: "Mas glifowy do gipsu", pricePerM2: 25, thickness: "1 opakowanie" },
  { id: "kleister", name: "Kleister do tapet", pricePerM2: 12, thickness: "1 opakowanie" },
  { id: "farba-1", name: "Farba akrylowa biała", pricePerM2: 55, thickness: "10L" },
  { id: "farba-2", name: "Farba akrylowa kolorowa", pricePerM2: 65, thickness: "10L" },
  { id: "impregnacja", name: "Impregnacja drewna", pricePerM2: 45, thickness: "5L" },
  { id: "grunt", name: "Grunt głębokopenetujący", pricePerM2: 35, thickness: "5L" },
  { id: "super-flis", name: "Superfiber - Włóknina", pricePerM2: 12, thickness: "1m2" },
  { id: "taśma", name: "Taśma maskująca 50mx50mm", pricePerM2: 8, thickness: "1 rolka" },
  { id: "siatka-50", name: "Siatka do murowania 50x50mm", pricePerM2: 15, thickness: "1m2" },
  { id: "siatka-25", name: "Siatka do murowania 25x25mm", pricePerM2: 28, thickness: "1m2" },
  { id: "klin-dop", name: "Kliny dopuszczające", pricePerM2: 2, thickness: "1 szt" },
  { id: "rura-pvc-32", name: "Rura PVC 32mm", pricePerM2: 8, thickness: "1 mb" },
  { id: "rura-pvc-50", name: "Rura PVC 50mm", pricePerM2: 12, thickness: "1 mb" },
  { id: "rura-pvc-110", name: "Rura PVC 110mm", pricePerM2: 25, thickness: "1 mb" },
  { id: "prof-alu-50", name: "Profil aluminiowy 50x50", pricePerM2: 45, thickness: "1 mb" },
  { id: "prof-alu-40", name: "Profil aluminiowy 40x40", pricePerM2: 35, thickness: "1 mb" },
  { id: "pas-montaz", name: "Pas montażowy 50mm", pricePerM2: 18, thickness: "50m" },
  { id: "zawiesia", name: "Zawiesia potryskowe", pricePerM2: 22, thickness: "1 paczka" },
  { id: "dychting", name: "Dychtowanie (uszczelniacz)", pricePerM2: 42, thickness: "600ml" },
  { id: "silikatowe-opał", name: "Farba silikatowa do opału", pricePerM2: 48, thickness: "10L" },
  { id: "mineralny-cert", name: "Certyfikowany materiał mineralny", pricePerM2: 38, thickness: "1 opakowanie" },
  { id: "okna-pvc", name: "Okna PVC 120x150cm", pricePerM2: 380, thickness: "1 szt" },
  { id: "okna-alu", name: "Okna aluminiowe 120x150cm", pricePerM2: 520, thickness: "1 szt" },
]